events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    server {
        listen 8000;
        root /usr/share/nginx/html;
        index index.html;

        location /auth/v1/    { proxy_pass http://auth:9999/; }
        location /rest/v1/    { proxy_pass http://rest:3000/; }
        location /storage/v1/ { proxy_pass http://storage:5000/; client_max_body_size 50m; }
        location /functions/v1/ { proxy_pass http://ocr:9000/; }
    }
}
